CREATE TABLE trails (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    rating SMALLINT DEFAULT 0,
    total_ratings SMALLINT DEFAULT 0,
    date_published TIMESTAMP DEFAULT now() NOT NULL,
    website TEXT NOT NULL,
    description TEXT NOT NULL,
    safety TEXT
);