CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    join_date TIMESTAMP DEFAULT now() NOT NULL,
    email TEXT NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT false,
    banned BOOLEAN NOT NULL DEFAULT false,
    banned_by: TEXT
);

ALTER TABLE pending
    ADD COLUMN
        submitted_by_id INTEGER REFERENCES users(id)
        ON DELETE SET NULL;